### ISSUE TITLE
Easy way to read and display DB data in php

### ISSUE THREAD

**Issue by lamaparbat70** [lamaparbat70/HumanResourcesManagementSystem#13]
<img width="709" alt="Screen Shot 2022-04-27 at 09 16 15" src="https://user-images.githubusercontent.com/101965590/165434421-a11d399c-30e4-4766-bf06-3d1545efedec.png">

**Comment by RohanShrestha11** [comment]
Thank you so much parbat for your suggestion regarding reading and displaying details from the database. I have made the necessary changes to the code of the read part of the CRUD operation and it is working fine now.
