### ISSUE TITLE
Create Schedule and Add task page

### ISSUE THREAD

**Issue by Samip7777** [lamaparbat70/HumanResourcesManagementSystem#21]
Make the cancel button on the left-margin equal to the container below.

**Comment by DipakKumarChaudhary** [comment]
i have add  the buttom code & solve this issue. Below there is screenshots of change output
![create](https://user-images.githubusercontent.com/102460657/167985080-33062f8d-b992-4053-a952-306af8c8a083.PNG)
![addtask](https://user-images.githubusercontent.com/102460657/167985107-f784a116-107a-4123-afb9-e823dfc8ac64.PNG)
