### ISSUE TITLE
employee notification panel shows notification from other employee.

### ISSUE THREAD

**Issue by Aayusht730** [lamaparbat70/HumanResourcesManagementSystem#25]
![rohan](https://user-images.githubusercontent.com/101965525/168541202-50370f37-8450-4e3a-9d87-bbc72f628ee0.png)

**Comment by RohanShrestha11** [comment]
Oh, I am really sorry about this bug. Now, I have resolved it as you can see in the image below. It only shows notifications of the logged in employee only.
![notifyComplete](https://user-images.githubusercontent.com/101965608/169733678-b44b19d0-2db1-4d02-ab67-1a0ca9fe50a0.png)
