### ISSUE TITLE
Details entered in the payment submit page is not being shown in the payment confirmation page

### ISSUE THREAD

**Issue by Aayusht730** [lamaparbat70/HumanResourcesManagementSystem#26]
![rohanPayment](https://user-images.githubusercontent.com/101965525/168542729-9de08598-35f0-49ee-bfde-61b0cbb20936.png)
![paymentConfirmation](https://user-images.githubusercontent.com/101965525/168542487-5eb2429f-23a8-4acd-b09f-ae1c6e0f8289.png)
5-4140-a9ac-9335b1b2efc4.png)

**Comment by RohanShrestha11** [comment]
Thank you Aayush for finding this bug. I have resolved and updated it. Now, you can prepare the test case.
![confirm2](https://user-images.githubusercontent.com/101965608/169732594-80fb6f26-1edd-4459-ac21-8fb61a5b143e.png)
