### ISSUE TITLE
Remove the Border of textfield of Signup Form 

### ISSUE THREAD

**Issue by lamaparbat70** [lamaparbat70/HumanResourcesManagementSystem#4]
The border outline appears when i click on the textfield which is iritating. Please remove that issue and please prefer the assigned design mockup.

**Comment by DipakKumarChaudhary** [comment]
Dear PM, I will try to solve this problem as soon as possible

**Comment by DipakKumarChaudhary** [comment]
The border outline appears when i click on the text Issue is solved

**Comment by RohanShrestha11** [comment]
Dear Dipak,

If you find the border issue again, you can simply set the outline of the particular text field as none in the css file.

Thank You.

**Comment by DipakKumarChaudhary** [comment]
Now I have changed the below-attached signup page.

**Comment by lamaparbat70** [comment]
Please refer this link: https://stackoverflow.com/questions/3397113/how-to-remove-focus-border-outline-around-text-input-boxes-chrome
