### ISSUE TITLE
Signup Backend: Server do not respond anything after submitting/posting form data from signup page.

### ISSUE THREAD

**Issue by lamaparbat70** [lamaparbat70/HumanResourcesManagementSystem#5]
When i submit the signup form data, the signup backend donot respond anything which is really confusing because it donot provide any registration information (Success or failure).

**Comment by RohanShrestha11** [comment]
I have edited the code after working on it. Now, All of the team members should meet up and perform the testing again.

**Comment by lamaparbat70** [comment]
Please refer this site for handling HTTP response in php: https://stackoverflow.com/questions/11087019/php-how-to-respond-to-http-request-and-continue-processing
